"""A score has to measure something, and say what.

Every imported record used to be stored with data_quality_score = 100.0,
is_verified = True and a timestamp. Nothing had checked anything. The patient
saw "100% quality" beside the record they had just handed over — approval
generated by an assignment statement — and the researcher received a quality
column that was the same fabricated number on every row.

These tests hold two lines: the number is measured from the record, and
nothing claims the values are correct, because nothing here checks that.
"""
import pytest

from api.record_quality import (assess, describe_gaps, expected_fields, score)


DIAGNOSIS = {"display": "AML", "code": "C92.0", "diagnosis_year": 2020,
             "clinical_status": "active"}


# ---------------------------------------------------------------------------
# It measures the record in front of it
# ---------------------------------------------------------------------------

def test_a_full_record_scores_full():
    assert assess(DIAGNOSIS, "diagnosis", "condition")["score"] == 100.0


def test_a_thin_record_scores_lower_and_says_what_is_missing():
    thin = {"display": "AML"}
    result = assess(thin, "diagnosis", "condition")
    assert result["score"] == 25.0
    assert set(result["missing"]) == {"code", "diagnosis_year", "clinical_status"}


def test_the_score_is_never_the_same_number_for_every_record():
    """The defect this module exists to prevent."""
    scores = {
        score(DIAGNOSIS, "diagnosis", "condition"),
        score({"display": "AML"}, "diagnosis", "condition"),
        score({"age_band": "60-69", "sex": "female"}, "demographics", "patient"),
    }
    assert len(scores) == 3, scores


def test_the_basis_is_returned_with_the_number():
    """A number nobody can take apart is a rumour."""
    result = assess({"display": "AML"}, "diagnosis", "condition")
    assert "1 of 4" in result["basis"]
    assert result["expected"] == 4


# ---------------------------------------------------------------------------
# What counts as present
# ---------------------------------------------------------------------------

def test_a_result_of_zero_is_a_result():
    """Treating falsiness as absence is how real values get scored as gaps."""
    full = {"test": "Blast count", "code": "L1", "value": 0,
            "unit": "%", "year": 2021}
    assert assess(full, "lab_results", "blast")["score"] == 100.0


def test_false_is_a_recorded_value():
    recorded = {"vital_status": "Alive", "death_year": False}
    assert "death_year" in assess(recorded, "outcome", "vital_status")["present"]


@pytest.mark.parametrize("empty", [None, "", "   ", [], {}])
def test_an_empty_value_is_a_gap(empty):
    result = assess({"display": "AML", "code": empty, "diagnosis_year": 2020,
                     "clinical_status": "active"}, "diagnosis", "condition")
    assert "code" in result["missing"]


# ---------------------------------------------------------------------------
# What it refuses to claim
# ---------------------------------------------------------------------------

def test_an_unrecognised_record_kind_scores_none_not_zero():
    """Zero would claim a measurement was taken and came back empty."""
    result = assess({"anything": 1}, "something_new", "unmapped")
    assert result["score"] is None
    assert "no completeness expectations" in result["basis"].lower()


def test_the_denominator_does_not_shrink_when_a_record_carries_less():
    """Terminology annotation adds keys only when a term maps.

    Deriving the expected set from the payload's own keys would give an
    unmapped diagnosis a smaller denominator and score it *higher* for
    carrying less.
    """
    mapped = dict(DIAGNOSIS, icd10_code="C92.0", coding_source="healthdb")
    unmapped = dict(DIAGNOSIS)
    assert (assess(mapped, "diagnosis", "condition")["expected"]
            == assess(unmapped, "diagnosis", "condition")["expected"])


def test_nothing_in_the_assessment_claims_the_values_are_correct():
    """Completeness is not accuracy, and must never read as it."""
    text = " ".join(str(v) for v in assess(DIAGNOSIS, "diagnosis", "condition").values())
    for word in ("verified", "validated", "confirmed", "accurate", "correct"):
        assert word not in text.lower(), f"assessment implies accuracy: {text}"


def test_an_unknown_type_falls_back_to_the_category():
    """Lab results arrive with the test name as the type; every one is a lab."""
    assert (expected_fields("lab_results", "Hemoglobin")
            == expected_fields("lab_results", "Anything Else"))
    assert expected_fields("lab_results", "Hemoglobin")


# ---------------------------------------------------------------------------
# What the contributor is told
# ---------------------------------------------------------------------------

def test_gaps_are_named_the_way_a_person_would_name_them():
    gaps = describe_gaps(assess({"display": "AML"}, "diagnosis", "condition"))
    assert "year of diagnosis" in gaps
    assert "diagnosis_year" not in gaps


def test_an_unlabelled_field_is_left_out_rather_than_shown_raw():
    """Showing someone a raw field name is worse than showing them nothing."""
    gaps = describe_gaps({"missing": ["some_internal_key"]})
    assert gaps == []


# ---------------------------------------------------------------------------
# Through the platform
# ---------------------------------------------------------------------------

@pytest.fixture()
def uploader(client, make_user, monkeypatch):
    import api.main as main
    from api.models import Consent, PatientProfile

    monkeypatch.setattr(main, "SYNTHETIC_FHIR_UPLOADS_ENABLED", True)
    headers, user_id = make_user("quality@example.com", role="patient")
    with client._session_factory() as db:
        profile = db.query(PatientProfile).filter(
            PatientProfile.user_id == user_id).one()
        db.add(Consent(patient_id=profile.id,
                       consent_type="research_data_sharing", status="active"))
        db.commit()
    return headers


def upload(client, headers, *resources):
    return client.post("/api/patient/connections/fhir", headers=headers, json={
        "source_name": "Test", "source_type": "fhir_api",
        "bundle": {"resourceType": "Bundle",
                   "entry": [{"resource": r} for r in resources]},
    })


def test_an_import_stores_a_measured_score_not_a_constant(client, uploader):
    from api.models import ExtractedMedicalData

    assert upload(client, uploader,
                  {"resourceType": "Condition", "code": {"text": "AML"},
                   "onsetDateTime": "2020-05-04",
                   "clinicalStatus": {"text": "active"}},
                  {"resourceType": "Condition", "code": {"text": "CLL"}},
                  ).status_code == 200

    with client._session_factory() as db:
        scores = sorted(r.data_quality_score
                        for r in db.query(ExtractedMedicalData).all())
    assert len(set(scores)) > 1, f"every record scored the same: {scores}"
    assert 100.0 not in scores or scores.count(100.0) < len(scores)


def test_an_import_claims_no_verification(client, uploader):
    """Nothing on this platform confirms a clinical value is correct."""
    from api.models import ExtractedMedicalData

    upload(client, uploader, {"resourceType": "Condition",
                              "code": {"text": "AML"},
                              "onsetDateTime": "2020-05-04"})
    with client._session_factory() as db:
        rows = db.query(ExtractedMedicalData).all()
    assert rows
    assert all(r.is_verified is False for r in rows)
    assert all(r.verification_date is None for r in rows)


def test_the_portal_shows_the_basis_and_the_gaps(client, uploader):
    upload(client, uploader, {"resourceType": "Condition",
                              "code": {"text": "AML"},
                              "onsetDateTime": "2020-05-04"})
    row = client.get("/api/patient/extracted-data", headers=uploader).json()[0]
    assert "of 4" in row["completeness"]
    assert "whether it is active" in row["missing_fields"]
    assert row["data_quality_score"] < 100.0


def test_a_stale_stored_score_is_not_repeated_to_the_patient(client, uploader):
    """Rows stored before this still hold 100.0. No read path may repeat it."""
    from api.models import ExtractedMedicalData

    upload(client, uploader, {"resourceType": "Condition",
                              "code": {"text": "AML"}})
    with client._session_factory() as db:
        for row in db.query(ExtractedMedicalData).all():
            row.data_quality_score = 100.0
        db.commit()

    served = client.get("/api/patient/extracted-data", headers=uploader).json()
    assert all(r["data_quality_score"] < 100.0 for r in served), served


# ---------------------------------------------------------------------------
# The invariant and the withdrawal
# ---------------------------------------------------------------------------

@pytest.fixture()
def admin(make_user):
    headers, _ = make_user("quality-admin@example.com", role="admin",
                           verified=True)
    return headers


def _falsely_verified(client):
    from api.models import ExtractedMedicalData, PatientProfile
    from datetime import datetime

    with client._session_factory() as db:
        patient_id = db.query(PatientProfile).first().id
        db.add(ExtractedMedicalData(
            patient_id=patient_id, connection_id="synthetic",
            data_category="diagnosis", data_type="condition",
            deidentified_data={"display": "AML"},
            data_quality_score=100.0, is_verified=True,
            verification_date=datetime.utcnow()))
        db.commit()


def test_the_audit_fails_on_a_record_claiming_verification(client, uploader):
    from api.self_audit import check_no_record_claims_verification

    upload(client, uploader, {"resourceType": "Condition",
                              "code": {"text": "AML"}})
    with client._session_factory() as db:
        assert check_no_record_claims_verification(db).passed

    _falsely_verified(client)
    with client._session_factory() as db:
        finding = check_no_record_claims_verification(db)
    assert not finding.passed
    assert finding.severity == "blocker"
    assert finding.count == 1


def test_the_repair_withdraws_the_claim_and_measures_the_score(client, uploader, admin):
    from api.models import ExtractedMedicalData
    from api.self_audit import check_no_record_claims_verification

    _falsely_verified(client)
    body = client.post("/api/admin/maintenance/unverified-claims",
                       headers=admin).json()
    assert body["applied"] is True
    assert body["records_corrected"] == 1

    with client._session_factory() as db:
        row = db.query(ExtractedMedicalData).filter(
            ExtractedMedicalData.is_verified.is_(False)).one()
        assert row.verification_date is None
        assert row.data_quality_score == 25.0
        assert check_no_record_claims_verification(db).passed


def test_the_repair_is_idempotent(client, uploader, admin):
    _falsely_verified(client)
    client.post("/api/admin/maintenance/unverified-claims", headers=admin)
    body = client.post("/api/admin/maintenance/unverified-claims",
                       headers=admin).json()
    assert body["applied"] is False
    assert body["records_corrected"] == 0


def test_a_non_admin_cannot_reach_the_repair(client, uploader):
    assert client.post("/api/admin/maintenance/unverified-claims",
                       headers=uploader).status_code in (401, 403)


# ---------------------------------------------------------------------------
# The expected set is a second place the parser's shape is written down
# ---------------------------------------------------------------------------

EVERY_RESOURCE = {"resourceType": "Bundle", "entry": [{"resource": r} for r in [
    {"resourceType": "Patient", "id": "p", "birthDate": "1962-03-17",
     "gender": "female", "deceasedBoolean": False},
    {"resourceType": "Condition", "code": {"text": "AML"},
     "onsetDateTime": "2020-05-04"},
    {"resourceType": "Observation",
     "code": {"text": "Blast", "coding": [{"system": "http://loinc.org",
                                            "code": "26446-4"}]},
     "effectiveDateTime": "2021-01-02", "valueString": "Positive"},
    {"resourceType": "Observation",
     "code": {"text": "Hemoglobin", "coding": [{"system": "http://loinc.org",
                                                 "code": "718-7"}]},
     "effectiveDateTime": "2021-01-02",
     "valueQuantity": {"value": 13.4, "unit": "g/dL"}},
    {"resourceType": "MedicationRequest",
     "medicationCodeableConcept": {"text": "Cytarabine"},
     "authoredOn": "2019-06-06"},
    {"resourceType": "Procedure", "code": {"text": "Biopsy"},
     "performedDateTime": "2018-07-07"},
]]}


def test_every_field_the_parser_emits_is_scored_or_named_as_unscored():
    """The dangerous direction of drift.

    If the parser gains a field and EXPECTED_FIELDS does not, every record
    silently scores complete while missing it — a completeness measure that
    quietly stops measuring the thing that was added. Deciding not to score a
    field is fine; forgetting to is not, so the decision has to be written
    down where this test can see it.
    """
    from api.fhir_ingest import parse_fhir_bundle
    from api.record_quality import UNSCORED_BY_DESIGN

    for record in parse_fhir_bundle(EVERY_RESOURCE):
        slots = expected_fields(record["data_category"], record["data_type"])
        scored = set()
        for slot in slots:
            scored.update(slot if isinstance(slot, tuple) else (slot,))

        unaccounted = set(record["data"]) - scored - set(UNSCORED_BY_DESIGN)
        assert not unaccounted, (
            f"{record['data_category']}/{record['data_type']} emits "
            f"{sorted(unaccounted)}, which is neither scored nor listed in "
            "UNSCORED_BY_DESIGN"
        )


def test_every_scored_field_is_one_the_parser_actually_emits():
    """The other direction: a slot nothing can ever fill caps the score.

    An expectation for a field the parser never produces marks every record
    of that kind permanently incomplete — the same defect as measuring a
    contribution against a category nobody can supply.
    """
    from api.fhir_ingest import parse_fhir_bundle

    emitted = {}
    for record in parse_fhir_bundle(EVERY_RESOURCE):
        key = (record["data_category"], record["data_type"])
        emitted.setdefault(key, set()).update(record["data"])

    for (category, data_type), keys in emitted.items():
        for slot in expected_fields(category, data_type):
            names = slot if isinstance(slot, tuple) else (slot,)
            assert keys & set(names), (
                f"{category}/{data_type} is scored on {names}, which the "
                "parser never emits, so it can never reach 100%"
            )


def test_a_qualitative_result_is_a_complete_result():
    """A word is a result. Scoring units would penalise a test for its kind.

    Both observations in the bundle carry a code and a year; the only thing
    that differs is whether the result is a number with a unit or a word.
    They must score the same.
    """
    from api.fhir_ingest import parse_fhir_bundle

    labs = [r for r in parse_fhir_bundle(EVERY_RESOURCE)
            if r["data_category"] == "lab_results"]
    assert len(labs) == 2
    assert all(score(r["data"], r["data_category"], r["data_type"]) == 100.0
               for r in labs), [
        (r["data_type"], score(r["data"], r["data_category"], r["data_type"]))
        for r in labs]
