import React from 'react';
import { Link } from 'react-router-dom';

export default function Developers() {
  const command = `curl --fail-with-body https://www.healthdb.ai/api/demo/cohort/build \\\n  -H 'Content-Type: application/json' \\\n  --data '{"cancer_types":["Multiple Myeloma"],"age_min":50}'`;
  return <article className="max-w-4xl mx-auto px-6 py-16 text-white space-y-8">
    <header><p className="text-emerald-300 text-sm">For developers and AI agents</p><h1 className="text-4xl mt-4 mb-5">From a question to a testable cohort.</h1><p className="text-lg text-white/70">Start with the public synthetic demo. No signup, credentials, or patient data required.</p></header>
    <section><h2 className="text-2xl mb-4">1. Run a query</h2><pre className="bg-white/5 p-5 rounded overflow-x-auto text-sm">{command}</pre><p className="text-white/70 mt-4">Fixture version 1 returns 4 matching fictional profiles and 16 records for this query. Results are deterministic and do not measure real-world data availability.</p></section>
    <section><h2 className="text-2xl mb-4">2. Inspect the contract</h2><ul className="list-disc pl-5 space-y-3 text-emerald-300"><li><a href="/api/openapi.json" className="underline">OpenAPI schema: request and response definitions</a></li><li><a href="/api/capabilities" className="underline">Capabilities: public entry points and access requirements</a></li><li><a href="/llms.txt" className="underline">Plain-text agent guide</a></li></ul><p className="text-white/70 mt-4">Filters combine with AND; alternatives within a diagnosis or stage list use OR. Every enabled inclusion must match; any matching exclusion removes a profile. Missing values never establish a negative finding. Unsupported filters return 422 rather than being silently ignored.</p></section>
    <section><h2 className="text-2xl mb-4">3. Handle errors explicitly</h2><p className="text-white/70">Check the HTTP status before reading results. A 422 indicates invalid input; 401 means authentication is required or expired; 403 means insufficient access; 429 means slow down; 5xx indicates a service problem. Retry read-only demo queries with a bounded delay. Do not automatically repeat study creation or export requests after a timeout without checking whether they succeeded.</p></section>
    <section><h2 className="text-2xl mb-4">Invited research workflows</h2><p className="text-white/70">Private endpoints require an invited account, a Bearer token from login, and the appropriate role. Exports require selected fields, current approvals, and eligible consented records. CSV is the supported pilot format. Keep credentials in server-side secrets and never send real patient information to this pilot.</p></section>
    <section><h2 className="text-2xl mb-4">Evaluate with us</h2><p className="text-white/70">The next milestones are reproducible data-quality benchmarks, evaluator feedback, and institutional governance review. We have not established production readiness or clinical validity.</p><div className="flex gap-6 mt-5"><Link className="text-emerald-300 underline" to="/demo">Try the visual demo</Link><Link className="text-emerald-300 underline" to="/contact">Discuss an integration or partnership</Link></div></section>
  </article>;
}
