/**
 * What a patient is told about their own record.
 *
 * This list used to print a green "100% quality" beside every record, and the
 * number was a constant assigned at import. Approval generated by an
 * assignment statement is not respect, and a grade is the wrong shape here
 * anyway: what helps someone looking at their own history is knowing which
 * parts of it are blank.
 */
const React = require('react');
const { createRoot } = require('react-dom/client');
const { act } = require('react-dom/test-utils');
const { MemoryRouter } = require('react-router-dom');

jest.mock('../lib/api', () => ({
  API_URL: '',
  apiFetch: jest.fn(),
  loadPanels: jest.requireActual('../lib/api').loadPanels,
  readSessionUser: () => ({ user_type: 'patient' }),
}));
jest.mock('react-hot-toast', () => ({ __esModule: true, default: jest.fn() }));

// Exit animations never settle under jsdom, so the outgoing tab stays mounted.
jest.mock('framer-motion', () => {
  const ReactLib = require('react');
  const motion = new Proxy({}, {
    get: (_, tag) => ({ children, ...rest }) => {
      ['initial', 'animate', 'exit', 'transition', 'variants', 'whileHover',
       'whileTap', 'whileInView', 'viewport', 'layout', 'layoutId']
        .forEach((key) => delete rest[key]);
      return ReactLib.createElement(typeof tag === 'string' ? tag : 'div', rest, children);
    },
  });
  return {
    motion,
    AnimatePresence: ({ children }) => ReactLib.createElement(ReactLib.Fragment, null, children),
    useInView: () => true,
    useScroll: () => ({ scrollYProgress: { on: () => {} } }),
    useTransform: () => 0,
  };
});

const { apiFetch } = require('../lib/api');
const PatientPortal = require('./PatientPortal').default;

const RECORD = {
  id: 'r1',
  data_category: 'diagnosis',
  data_type: 'condition',
  extracted_date: '2026-01-01T00:00:00Z',
  original_year: 2020,
  data_quality_score: 50,
  completeness: '2 of 4 expected fields are recorded.',
  missing_fields: ['a standard code', 'whether it is active'],
  summary: { display: 'AML', diagnosis_year: 2020 },
  origin: 'Imported from a health record file you uploaded.',
};

let root, container;

function mockApi(overrides = {}) {
  apiFetch.mockImplementation((url) => {
    const body =
      Object.keys(overrides).find((k) => url.includes(k))
        ? overrides[Object.keys(overrides).find((k) => url.includes(k))]
      : url.includes('/api/patient/profile') ? { points_balance: 0, engagement_level: 'new' }
      : url.includes('/api/patient/data-summary') ? { total_records: 1 }
      : url.includes('/api/patient/contribution') ? { stages: [], summary: 'x' }
      : url.includes('/api/patient/consents')
        ? [{ id: 'c1', status: 'active', consent_type: 'research_data_sharing' }]
      : [];
    return Promise.resolve({ ok: true, json: () => Promise.resolve(body) });
  });
}

async function openRecordsTab() {
  await act(async () => {
    root.render(React.createElement(MemoryRouter, null,
      React.createElement(PatientPortal)));
  });
  await act(async () => { await Promise.resolve(); });
  const tab = [...container.querySelectorAll('button')]
    .find((b) => b.textContent.includes('Test Data'));
  expect(tab).toBeTruthy();
  await act(async () => {
    tab.dispatchEvent(new MouseEvent('click', { bubbles: true }));
  });
  await act(async () => { await Promise.resolve(); });
}

beforeEach(() => {
  global.IS_REACT_ACT_ENVIRONMENT = true;
  sessionStorage.setItem('token', 'test-token');
  container = document.createElement('div');
  root = createRoot(container);
});

afterEach(() => {
  act(() => root.unmount());
  sessionStorage.clear();
  jest.resetAllMocks();
});

test('a record shows what it does not say, not a grade', async () => {
  mockApi({ '/api/patient/extracted-data': [RECORD] });
  await openRecordsTab();

  expect(container.textContent).toContain('2 of 4 expected fields are recorded');
  expect(container.textContent).toContain('whether it is active');
  // The fabricated badge is gone.
  expect(container.textContent).not.toContain('quality');
});

test('a complete record is not nagged at about gaps', async () => {
  mockApi({
    '/api/patient/extracted-data': [{
      ...RECORD,
      data_quality_score: 100,
      completeness: '4 of 4 expected fields are recorded.',
      missing_fields: [],
    }],
  });
  await openRecordsTab();

  expect(container.textContent).toContain('4 of 4 expected fields are recorded');
  expect(container.textContent).not.toContain('Not recorded:');
});

test('closing intake does not hide what someone already contributed', async () => {
  // The upload flag is off in this file (never set), which is production
  // today. A contributor must still be able to see their own records: you
  // cannot decide to withdraw what you cannot see.
  mockApi({ '/api/patient/extracted-data': [RECORD] });
  await openRecordsTab();

  expect(container.textContent).toContain('2 of 4 expected fields are recorded');
  expect(container.textContent).toContain('Record intake is closed on this deployment');
  // ...and no control offers an import that would be refused.
  expect(container.textContent).not.toContain('Import Test Bundle');
});

test('with nothing contributed and intake closed, the tab says so plainly', async () => {
  mockApi({ '/api/patient/extracted-data': [] });
  await openRecordsTab();

  expect(container.textContent).toContain('Record intake is closed');
  expect(container.textContent).not.toContain('expected fields are recorded');
});

test('the dashboard percentage carries what it is made of', async () => {
  mockApi({
    '/api/patient/data-summary': {
      total_records: 1,
      categories: { diagnosis: 1 },
      completeness_score: 20,
      completeness_basis: '1 of 5 kinds of record are represented. Not yet contributed: demographics, treatment, lab results, outcome.',
    },
  });
  await act(async () => {
    root.render(React.createElement(MemoryRouter, null,
      React.createElement(PatientPortal)));
  });
  await act(async () => { await Promise.resolve(); });

  expect(container.textContent).toContain('1 of 5 kinds of record are represented');
});


test('an empty field does not crowd out the result the person wants to see', async () => {
  // A qualitative lab: the numeric value is null and the real result is
  // value_string, which sat past the four-chip cut behind blank labels.
  mockApi({
    '/api/patient/extracted-data': [{
      ...RECORD,
      data_category: 'lab_results',
      data_type: 'Blast count',
      completeness: '4 of 4 expected fields are recorded.',
      missing_fields: [],
      summary: {
        code: '26446-4',
        code_system: 'LOINC',
        test: 'Blast count',
        value: null,
        unit: null,
        value_string: 'Positive',
      },
    }],
  });
  await openRecordsTab();

  expect(container.textContent).toContain('Positive');
  expect(container.textContent).not.toContain('value:');
  expect(container.textContent).not.toContain('unit:');
});


test('a code this platform matched is attributed, not passed off as the record', async () => {
  // The card used to say "Not recorded: a standard code" while displaying a
  // code — because the code came from us, not from the person's record.
  mockApi({
    '/api/patient/extracted-data': [{
      ...RECORD,
      missing_fields: ['a standard code', 'whether it is active'],
      summary: {
        display: 'Acute myeloid leukemia',
        diagnosis_year: 2021,
        code: null,
        icd10_code: 'C92.0',
        icd10_display: 'Acute myeloblastic leukemia',
        coding_source: 'healthdb-terminology-map',
      },
    }],
  });
  await openRecordsTab();

  expect(container.textContent).toContain('HealthDB matched it to ICD-10 C92.0');
  expect(container.textContent).toContain('That match is ours, not your clinician');
  // Not mixed in with their own fields as if a clinician had written it.
  expect(container.textContent).not.toContain('icd10 code:');
  expect(container.textContent).not.toContain('coding source:');
});

test('a record with no matched code says nothing about matching', async () => {
  mockApi({
    '/api/patient/extracted-data': [{
      ...RECORD,
      summary: { display: 'AML', code: 'C92.0', diagnosis_year: 2020 },
    }],
  });
  await openRecordsTab();
  expect(container.textContent).not.toContain('HealthDB matched');
});

test('field names are shown as words, not as a schema', async () => {
  mockApi({
    '/api/patient/extracted-data': [{
      ...RECORD,
      summary: { value_string: 'Positive', clinical_status: 'active' },
    }],
  });
  await openRecordsTab();
  expect(container.textContent).toContain('result: Positive');
  expect(container.textContent).not.toContain('value string:');
  expect(container.textContent).not.toContain('clinical status:');
});
