#!/usr/bin/env node
/**
 * Regenerates public/sitemap.xml from the route table in PageMeta, so the
 * sitemap cannot drift from the routes that actually exist. Private routes
 * (noindex) are excluded.
 *
 * lastmod comes from the git commit date of the page's source file, so it
 * reflects when the content actually changed rather than when this ran.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const SITE = 'https://www.healthdb.ai';

const meta = fs.readFileSync(path.join(ROOT, 'src/components/PageMeta.js'), 'utf8');
const body = meta.slice(meta.indexOf('export const ROUTE_META'), meta.indexOf('/** Public, indexable'));

const routes = [];
const entry = /'([^']+)':\s*\{([\s\S]*?)\n  \},/g;
let m;
while ((m = entry.exec(body))) {
  if (!/noindex:\s*true/.test(m[2])) routes.push(m[1]);
}
// Single-line entries.
const inline = /'([^']+)':\s*\{ title:[^}]*\},/g;
while ((m = inline.exec(body))) {
  if (!/noindex:\s*true/.test(m[0]) && !routes.includes(m[1])) routes.push(m[1]);
}

const PAGE_FILE = {
  '/': 'src/pages/LandingPage.js', '/patients': 'src/pages/ForPatients.js',
  '/researchers': 'src/pages/ForResearchers.js', '/institutions': 'src/pages/ForInstitutions.js',
  '/status': 'src/pages/PlatformStatus.js', '/platform': 'src/pages/PlatformFocusAreas.js',
  '/security-posture': 'src/pages/SecurityPostureMap.js', '/data-flow': 'src/pages/DataFlowDiagram.js',
  '/repo-analyzer': 'src/pages/RepoAnalyzer.js', '/marketplace': 'src/pages/DataMarketplace.js',
  '/resources': 'src/pages/Resources.js', '/pricing': 'src/pages/Pricing.js',
  '/about': 'src/pages/About.js', '/contact': 'src/pages/Contact.js',
  '/privacy': 'src/pages/Privacy.js', '/terms': 'src/pages/Terms.js',
  '/cohort-builder': 'src/pages/CohortBuilder.js',
};

function lastModified(route) {
  const file = PAGE_FILE[route];
  if (!file || !fs.existsSync(path.join(ROOT, file))) {
    return new Date().toISOString().slice(0, 10);
  }
  try {
    return execSync(`git log -1 --format=%cs -- "${file}"`, { cwd: ROOT })
      .toString().trim() || new Date().toISOString().slice(0, 10);
  } catch {
    return new Date().toISOString().slice(0, 10);
  }
}

const PRIORITY = { '/': '1.0', '/status': '0.9', '/patients': '0.8', '/researchers': '0.8',
                   '/institutions': '0.8' };

const urls = routes.sort().map((route) => `  <url>
    <loc>${SITE}${route === '/' ? '/' : route}</loc>
    <lastmod>${lastModified(route)}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${PRIORITY[route] || '0.6'}</priority>
  </url>`).join('\n');

fs.writeFileSync(path.join(ROOT, 'public/sitemap.xml'),
`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate_sitemap.js. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`);
console.log(`sitemap.xml written: ${routes.length} public routes`);
