"""How complete a record is, measured rather than asserted.

Every imported record used to be stored with ``data_quality_score = 100.0``,
``is_verified = True`` and a verification timestamp. Nothing had verified
anything. The number was a constant wearing the costume of a measurement.

That is not a harmless placeholder in either direction.

A patient saw "100% quality" beside the record they had just handed over.
That reads as approval — as a platform telling them their contribution is
good — and it was generated by an assignment statement. Flattery is not
respect.

A researcher received `quality_score` as a column in the export. A quality
signal is something you filter or weight by, so a uniformly fabricated one is
worse than none: it invites a decision and gives it nothing to stand on.

So this measures what can actually be measured — how much of what a record of
this kind can carry is actually present — and says nothing about whether the
contents are correct. Completeness is not accuracy, and this module never
implies it is. Verification would mean a person or an authoritative source
confirmed the values; nothing on this platform does that yet, so nothing here
claims it.

Two rules:

**A score is always returned with its basis.** ``assess`` reports which
fields were found and which were missing, because a number nobody can take
apart is a rumour. The portal names the gaps instead of printing a percentage
at someone, which also makes it useful: "no stage recorded" is something a
patient can go and fix.

**A missing field is reported, never penalised into a verdict.** A record at
40% is not a bad record; often it is a real patient whose chart is thin. It
is a record a researcher should be able to see the shape of before they
build a cohort on it.
"""
from typing import Any, Mapping, Sequence

# What a record of each kind can carry, in the order a person would read it.
#
# Deliberately not derived from the payload's own keys. Terminology annotation
# adds keys only when a term maps, so a denominator taken from the record
# itself would shrink for unmapped diagnoses and score them *higher* for
# carrying less. The expected set has to be stated independently of what
# arrived.
EXPECTED_FIELDS = {
    ("demographics", None): ("age_band", "sex", "race", "ethnicity"),
    ("outcome", None): ("vital_status", "death_year"),
    ("diagnosis", None): ("display", "code", "diagnosis_year", "clinical_status"),
    ("lab_results", None): ("test", "code", "value", "unit", "year"),
    ("treatment", "medication"): ("medication", "code", "status", "start_year"),
    ("treatment", "procedure"): ("procedure", "code", "status", "year"),
}

# Field names as a patient would say them, so the portal can name a gap
# without showing someone the inside of a schema.
FIELD_LABELS = {
    "age_band": "age range",
    "sex": "sex",
    "race": "race",
    "ethnicity": "ethnicity",
    "vital_status": "vital status",
    "death_year": "year of death",
    "display": "diagnosis",
    "code": "a standard code",
    "diagnosis_year": "year of diagnosis",
    "clinical_status": "whether it is active",
    "test": "test name",
    "value": "result",
    "unit": "units",
    "year": "year",
    "medication": "medication",
    "status": "status",
    "start_year": "year started",
    "procedure": "procedure",
}


def expected_fields(category, data_type) -> Sequence[str]:
    """What a record of this kind can carry, or () when we do not know.

    Returning empty for an unrecognised kind is the honest answer. Scoring it
    against a guessed field list would produce a number about nothing.
    """
    exact = EXPECTED_FIELDS.get((category, data_type))
    if exact is not None:
        return exact
    return EXPECTED_FIELDS.get((category, None), ())


def _present(value: Any) -> bool:
    """Whether a field actually carries something.

    ``0`` and ``False`` are present. A lab result of zero is a result, and
    treating falsiness as absence is how real values get scored as gaps.
    """
    if value is None:
        return False
    if isinstance(value, str):
        return value.strip() != ""
    if isinstance(value, (list, tuple, dict, set)):
        return len(value) > 0
    return True


def assess(data: Mapping[str, Any], category=None, data_type=None) -> dict:
    """Completeness, with the fields it was derived from.

    ``score`` is None — not zero — when the record is of a kind this module
    has no expectations for. Zero would claim a measurement was taken and
    came back empty; None says no measurement was possible.
    """
    fields = expected_fields(category, data_type)
    if not fields:
        return {"score": None, "present": [], "missing": [], "expected": 0,
                "basis": "No completeness expectations are defined for this "
                         "kind of record, so none is claimed."}

    payload = data if isinstance(data, Mapping) else {}
    present = [name for name in fields if _present(payload.get(name))]
    missing = [name for name in fields if name not in present]
    return {
        "score": round(100.0 * len(present) / len(fields), 1),
        "present": present,
        "missing": missing,
        "expected": len(fields),
        "basis": f"{len(present)} of {len(fields)} expected fields are recorded.",
    }


def score(data: Mapping[str, Any], category=None, data_type=None):
    """Just the number, for callers that store or export it."""
    return assess(data, category, data_type)["score"]


def describe_gaps(assessment: Mapping[str, Any]) -> list:
    """The missing fields, named the way a person would name them.

    Used to tell a contributor what their record does not say, rather than
    printing a percentage at them. Anything unlabelled is left out: showing
    someone a raw field name is worse than showing them nothing.
    """
    return [FIELD_LABELS[name] for name in assessment.get("missing", ())
            if name in FIELD_LABELS]
